plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ns4.quiz'
    compileSdk 34

    defaultConfig {
        applicationId "com.ns4.quiz"
        minSdk 21
        targetSdk 34
        versionCode 211
        versionName "2.1.1"
    }

    signingConfigs {
        release {
            storeFile file("release.jks")
            storePassword System.getenv("KEYSTOREPASSWORD")
            keyAlias System.getenv("KEYALIAS")
            keyPassword System.getenv("KEYPASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.gms:play-services-ads:23.0.0'
}